name: My First Github Action
on: [push] # run on push
jobs: # to run on push
  print-hello-world:
    runs-on: ubuntu-latest
    steps: #steps will happen one after another
      - run: echo "hello world!!!!! 👻" # basically the bash command
      - run: echo "me again!!!!! 👻" # basically the bash command
  print-goodbye-world:
    runs-on: ubuntu-latest
    steps: #steps will happen one after another
      - run: echo "goodbye world!!!!! 👻" # basically the bash command
      - run: echo "goodbye again!!!!! 👻" # basically the bash command
