name: My First Github Action
on: [push] # run on push
jobs: # to run on push
  build-app:
    runs-on: ubuntu-latest
    steps: #steps will happen one after another
      - uses: actions/checkout@v2 # use a prebuilt action from Github where we clone the repo
      - uses: actions/setup-node@v2 # use a prebuilt action from Github set up node in the env
        with:
          node-version: '14.17.0' # set up specific version of node
      - run: tree # basically the bash command we're reading the cloned files from

