name: My First Github Action
on: [push] # run on push
jobs: # to run on push
  build-app:
    runs-on: ubuntu-latest
    steps: #steps will happen one after another
      - uses: actions/checkout@v2 # use a prebuilt action from Github
      - run: tree # basically the bash command

